services:
  backend:
    container_name: blog-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    stdin_open: true
    tty: true
    restart: unless-stopped
    env_file:
      - ./.env.dev
    ports:
      - "8000:8000"
    expose:
      - 8000
    volumes:
      - ./backend/:/usr/src/app/
    depends_on:
      - db
    networks:
      - network_blog

  frontend:
    container_name: blog-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - network_blog

  db:
    container_name: blog-database
    image: postgres:17
    ports:
      - "5432:5432"
    env_file:
      - ./.env.db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - network_blog

volumes:
  postgres-data:

networks:
  network_blog:
    driver: bridge
