# Generated by Django 5.1.5 on 2025-02-08 12:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_comment_post_remove_post_tag_post_tag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='liked',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
