# Generated by Django 5.1.5 on 2025-03-06 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_readinglist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readinglist',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='reading_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reading_list_posts', to='core.readinglist'),
        ),
    ]
