# Generated by Django 5.1.5 on 2025-03-06 15:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_readinglist_post_post_reading_list'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='reading_list',
        ),
        migrations.DeleteModel(
            name='ReadingList',
        ),
        migrations.AddField(
            model_name='post',
            name='reading_list',
            field=models.ManyToManyField(related_name='reading_list_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
